"""
Camera Configuration for S-Oasis Safety Monitoring System
Auto-generated by setup_system.py
"""

# TP-Link Tapo C520 Camera Configuration
CAMERA_CONFIG = {
    # Network Configuration
    "ip": "192.168.0.245",
    "rtsp_port": 554,
    "onvif_port": 2020,
    
    # Authentication
    "username": "Admin_FF",
    "password": "Fourty40!",
    
    # Stream Configuration
    "stream_path": "stream1",
    "use_tcp": True,
    
    # Performance Settings
    "fps_limit": 15,
    "buffer_size": 1,
    "frame_skip": 3,
    "use_low_resolution": False,  # Use stream2 (lower res) for better performance
    "detection_interval": 1,  # Process every N frames (1=every frame, 2=every other frame)
}

# Detection Configuration
DETECTION_CONFIG = {
    "required_ppe": ["Hardhat", "Mask", "Safety Vest"],
    "yolo_confidence": 0.5,
    "face_tolerance": 0.6,
    "face_model": "hog",
    "log_interval": 30,
    "alert_cooldown": 30,
    "detect_unknown_people": True,  # Enable/disable unknown person detection
    "unknown_detection_cooldown": 30,  # Seconds between same person detections
    "detect_ppe": True,  # Enable/disable safety equipment detection (faces only when False)
}

# Directory Configuration
PATHS = {
    "employee_faces": "dataset",
    "output_directory": "results",
    "model_path": "best.pt",
    "log_filename": "live_ppe_log.csv"
}

# Display Configuration
DISPLAY_CONFIG = {
    "window_name": "S-Oasis Live Monitoring",
    "show_fps": True,
    "show_confidence": True,
    "face_color": (255, 0, 255),
    "ppe_compliant_color": (0, 255, 0),
    "ppe_other_color": (0, 0, 255),
    "status_compliant_color": (0, 255, 0),
    "status_violation_color": (0, 0, 255),
}

def get_rtsp_url():
    """Generate RTSP URL from configuration"""
    config = CAMERA_CONFIG
    return f"rtsp://{config['username']}:{config['password']}@{config['ip']}:{config['rtsp_port']}/{config['stream_path']}"

def print_config():
    """Print current configuration (hiding password)"""
    print("=" * 50)
    print("S-OASIS SAFETY MONITORING SYSTEM CONFIGURATION")
    print("=" * 50)
    
    config = CAMERA_CONFIG.copy()
    config['password'] = '*' * len(config['password'])
    
    print(f"Camera IP: {config['ip']}")
    print(f"RTSP Port: {config['rtsp_port']}")
    print(f"Username: {config['username']}")
    print(f"Password: {config['password']}")
    print(f"Stream Path: {config['stream_path']}")
    print(f"RTSP URL: rtsp://{config['username']}:***@{config['ip']}:{config['rtsp_port']}/{config['stream_path']}")
    print(f"Required PPE: {', '.join(DETECTION_CONFIG['required_ppe'])}")
    print(f"Model Path: {PATHS['model_path']}")
    print(f"Employee Faces Directory: {PATHS['employee_faces']}")
    print("=" * 50)

if __name__ == "__main__":
    print_config()
